### ISSUE TITLE
Traffic quota not refilled after payment with a new paypal account

### ISSUE THREAD

**Issue by teopscorp** [lazydroid/auto-update-apk-client#75]
At our company we decided to change the paypal account linked with auto update apk's account after noticing that the quota hasn't been refilled for a couple of weeks (credit card expired). We cancelled the subscription using the button in the account management page and then resubscribed with a new paypal account.

It has been 5 days since the new subscription (with the initial payment) and the traffic quota hasn't been refilled yet.

**Comment by lazydroid** [comment]
Sorry again, we don't have access to your credit cards, since Paypal does that for us. Please, check your Paypal account or maybe an e-mail they might have sent you about cards expiration, etc.
