### ISSUE TITLE
No technical support since 1 month. IS THE SERVICE STILL MAINTAINED?

### ISSUE THREAD

**Issue by teopscorp** [lazydroid/auto-update-apk-client#76]
At our organisation we noticed after a couple of weeks that our traffic quota was not refilled. We decided to contact the technical support using the "Contacts" link at the bottom of autoupdateapk.com website. After a week without answer we replied to ask for a status of our inquiry. It has been a month now and no reply was received.

In the meantime we figured out that the credit card linked to our paypal account was expired. We decided to resubscribe with a new paypal account and the traffic quota hasn't been refilled yet. ( issue #75 )

As paying customers we consider it unacceptable that the technical support seems totally absent. With the recent issue of the payment not processed for quota refill, we are seriously considering to change our deployment/updater solution as we suspect that the auto update apk service is not well maintained anymore.

**Comment by irineuruiz** [comment]
We are having a similar problem.
We send a email to the support in 04/11/2016 and until now does not have any answer...

As paying customers we consider it unacceptable that the technical support seems totally absent.

**Comment by challgren** [comment]
I switched over to www.pushlink.com they fixed my Android 7.0 not being able to update problem in 2 weeks. They offer a little bit more features over Auto Update APK.

**Comment by lazydroid** [comment]
> In the meantime we figured out that the credit card linked to our paypal account was expired.

Sorry, guys, we don't have any access to your credit cards since all payments and handled through Paypal.
