### ISSUE TITLE
Current version broken

### ISSUE THREAD

**Issue by dariusfi** [lazydroid/auto-update-apk-client#81]
Android Studio doesn't compile most current version.
Obvious problems: variable "notificationIntent" in AutoUpdateApk. java is never defined. Library "import com.nbeghin.smartchandiser.BuildConfig;" unknown.

**Comment by dariusfi** [comment]
Fixed the bugs and uploaded here: https://github.com/dariusfi/auto-update-apk-client
Also added additional setup descriptions for Android > 7.0, migrated to gradle build system, added option to show update as popup instead of notification and did some small refactorings.
Feel free to merge if you're happy with the changes.

**Comment by lazydroid** [comment]
@dariusfi  thank you for the changes, will be merged shortly.
