### ISSUE TITLE
Run Issue

### ISSUE THREAD

**Issue by hanie1996** [lazydroid/auto-update-apk-client#86]
Hello everyone , 
I'm getting an issue when running the app on the AVD , it shows me this error in the Build Output for AutoUpdateApk.java  .
```
error: package com.nbeghin.smartchandiser does not exist | 
error: cannot find symbol variable notificationIntent |  
error: cannot find symbol variable notificationIntent |  
error: cannot find symbol variable BuildConfig |  
error: cannot find symbol variable notificationIntent |  
error: cannot find symbol variable notificationIntent |  
```
please help me !!
`

**Comment by lazydroid** [comment]
Sorry, I have merged someone's pull request without thoroughly checking and some pieces of the someone's code went into the codebase, please checkout an earlier version and use it.
