### ISSUE TITLE
I'm continue seeing wildcards instead of number of downloads.

### ISSUE THREAD

**Issue by amogelnicki** [lazydroid/auto-update-apk-client#87]
![autoupdate](https://user-images.githubusercontent.com/51382794/68395051-c3f5d900-014d-11ea-84c2-bcdcae0c7c13.png)

**Comment by irineuruiz** [comment]
Same thing for us and also one of our apk is with htpp status code 404 in the link since Monday.

https://github.com/lazydroid/auto-update-apk-client/issues/88

Looks like this site are abandoned

**Comment by lazydroid** [comment]
One of the clients had too many downloads, which made the stats to timeout on DB access, and the counters were temporarily replaced with the placeholders. Now, if the number of downloads is less 10k, the actual number is shown, otherwise it's "over 10k".
