### ISSUE TITLE
Error 404 in link with our apk

### ISSUE THREAD

**Issue by irineuruiz** [lazydroid/auto-update-apk-client#88]
Today we published an apk version 1.27.0 this morning and everything worked fine.

3 hours later, the same link receives the HTTP 404 status code.

Please fix it!

**Comment by lazydroid** [comment]
you might have run out of your traffic quota, please check "Account" page?

**Comment by irineuruiz** [comment]
Today we are having the same problem and our traffic quota is 5.0 GB avaiable in the account page

Link with 404 error:
http://www.auto-update-apk.com/fetch/AMIfv970q206xtQTSgUnTY5t7qtClW2orhkb0E6EOcKHxWR1UnNQgChkxDtuAOLnsAm4ug3fXd0NLX12BmXbWCrKHsLtOGS5RtL4uvGzKOBxBRkH0TuYeZueQEmzdJZgLVSCawOkwn6wEvzFH05xLBNQbv4oxN6XfpC7LFjEbvn2CHcyycHU_CM/rasmovel-1.20.9_t-uat.apk

**Comment by lazydroid** [comment]
checking now, please, stand by

**Comment by lazydroid** [comment]
made a few changes, hopefully the issue will get resolved in about 30min, please wait a bit.

**Comment by lazydroid** [comment]
I have made a few checks, you are on the "free" plan, right? How come you had 5GB available? You could have 5GB if you are a subscriber, but you are not. I have added 1GB to your account, it should fix the 404 error until you run out of traffic quota.

If you think I'm wrong and you somehow had a subscriber account and should have 5GB available, please, reply here and I shall make all necessary changes.
