### ISSUE TITLE
Error 404 and we have 5 GB avaiable in the account page

### ISSUE THREAD

**Issue by irineuruiz** [lazydroid/auto-update-apk-client#89]
Yesterday we published an apk version 1.20.9 and everything worked fine.

Today, the same link receives the HTTP 404 status code.

Please fix it
Our traffic quota is 5.0 GB avaiable in the account page at this moment

Link with 404 error:
http://www.auto-update-apk.com/fetch/AMIfv970q206xtQTSgUnTY5t7qtClW2orhkb0E6EOcKHxWR1UnNQgChkxDtuAOLnsAm4ug3fXd0NLX12BmXbWCrKHsLtOGS5RtL4uvGzKOBxBRkH0TuYeZueQEmzdJZgLVSCawOkwn6wEvzFH05xLBNQbv4oxN6XfpC7LFjEbvn2CHcyycHU_CM/rasmovel-1.20.9_t-uat.apk

**Comment by lazydroid** [comment]
made a few changes, hopefully the issue will get resolved in about 30min, please wait a bit.

**Comment by lazydroid** [comment]
I have made a few checks, you are on the "free" plan, right? How come you had 5GB available? You could have 5GB if you are a subscriber, but you are not. I have added 1GB to your account, it should fix the 404 error until you run out of traffic quota.

If you think I'm wrong and you somehow had a subscribed account and should have 5GB available, please, reply here and I make all necessary changes.

**Comment by irineuruiz** [comment]
We are a subscriber, our account is with the user app@rassystem.com.br and we pay with PayPal monthly

**Comment by irineuruiz** [comment]
The link is working at this moment

**Comment by lazydroid** [comment]
You have uploaded the application from account 'victor.XXXXXXX@rassystem.com.br' (XXX are added to protect the e-mail from spam), which is free account. Please, use the same account you pay for to distribute the applications you create. If you pay for one account and upload the application to another -- it might not work.

**Comment by lazydroid** [comment]
Thank you for using AutoUpdateAPK! If you have any problems or concerns, please, don't hesitate to open an issue.

**Comment by irineuruiz** [comment]
Hello,

Victor was a former employee of the company who has not worked here for years.
I used the app account to upload the 1.20.9 version of br.com.rassystem.rasmovel.uat, which is the correct account wich we pay for distribute the apps.

He probably misused his account when he uploaded the first version years ago.
How can this be corrected?

I didn't see how to make this kind of adjustment in our interface ...

Thank you
