### ISSUE TITLE
Change app owner

### ISSUE THREAD

**Issue by rodrigo-rassystem** [lazydroid/auto-update-apk-client#90]
Hello, this issue is related to https://github.com/lazydroid/auto-update-apk-client/issues/89

Rassystem company owns two apps: 
br.com.rassystem.rasmovel
and
br.com.rassystem.rasmovel.uat

Both apps should be managed by "app@rassystem.com.br", but unfortunately the app "br.com.rassystem.rasmovel.uat" is managed by "victor.ber@rassystem.com.br" (he is a former employee). Can you set the package "br.com.rassystem.rasmovel.uat" to be managed by "app@rassystem.com.br"? 
As you can see this email is already a collaborator, but we need that it become the owner so we can take advantage of the paid plan. 
Thanks.

**Comment by irineuruiz** [comment]
The email victor.ber@rassystem.com.br no longer exists, so we can't do it ourselves

**Comment by lazydroid** [comment]
I'm very sorry about this situation, but I don't control passwords and other authentication things which are taken care of by Google. I'll take a look at the database and check if there's a convenient way to assign all application to your company e-mail address. In the worst case, I can just delete the wrong account and all applications, and then you may reupload the latest version back again (you have the source code and the .apk, right?)

Please, wait a day or two for me getting back to you, we have national holidays -- sorry about that.

**Comment by rodrigo-rassystem** [comment]
Ok either solution is fine for us, just remember that the package is br.com.rassystem.rasmovel.uat and our company account is app@rassystem.com.br.

**Comment by lazydroid** [comment]
I have added "Traffic Quota: 5.0 GB" to the Victor's account while investigating the issue so your clients get their apps updated without any problem. Will add more if needed, until we get it properly working with your main account.

**Comment by lazydroid** [comment]
I have made the changes, please, check from your side if everything looks as it should?

**Comment by rodrigo-rassystem** [comment]
Yes. Thanks!

**Comment by lazydroid** [comment]
@rodrigo-rassystem glad to hear that! thank you for using AutoUpdateAPK! =)
